### ISSUE TITLE
Morning session: peer-to-peer code reviews

### ISSUE THREAD

**Issue by hendridg** [aimemalaika/Leader-board#4]
# Learning objectives

- Understand the code review process as a team effort.
- Understand the Microverse program code review flow.
- Write clear and professional code review comments.

**Comment by hendridg** [comment]
# Clean and beautiful :fire:

**Comment by andres-condezo** [comment]
## HI @aimemalaika 
Good job so far!

## Highlights
- Clean code 🟢 
- Great user intarface🟢 
![](https://64.media.tumblr.com/5a97be1dba647633e37cce9b571e30d2/tumblr_mnvx967abB1sr1ki0o1_250.gifv) 

Cheers and Happy coding!

**Comment by Reem-lab** [comment]
## Highlights to say 👍 
 - Great job here!
 - Very beautiful design I like it 
 - Outstanding for using features like a pop-up window
 
 <img src="https://media0.giphy.com/media/xHMIDAy1qkzNS/giphy.gif"/>
